services:
  pg_cadastro:
    image: postgres:alpine3.19
    container_name: pg_cadastro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"